export enum NationalIdType {
  NATIONAL_ID = 'NATIONAL_ID',
  PASSPORT = 'PASSPORT',
  TAX_ID = 'TAX_ID',
  SOCIAL_SECURITY = 'SOCIAL_SECURITY',
  DRIVERS_LICENSE = 'DRIVERS_LICENSE',
  OTHER = 'OTHER',
}
